#!/bin/bash

grep '<td>.*</td>' |
#This will isolate: <td>hword</td> and <td>eword</td>
    
tr "A-Z\`"  "a-z\'" |
#changes all the lowercase lettes to upper case letters 
# and okina(`) to '

sed "s/<td>/\n/g" | 
#Replaces all <td> with new lines 

sed "s/<.\{1,2\}>//g" | 
#Deletes <u> and </u>

sed "s/<.\{1,3\}>/\n/g" | 
#Replaces all </td> with new lines 

sed "s/<font .*font>/\n/g" |
#Replaces the above pattern
#<font.....</font> with new lines

sed "s/<small.*small>/\n/g" | 
#Replaces the above pattern 
#<small.....<small> with new lines    

sed "s/, /\n/g" | 
#Replaces pattern ,SP with new line
#It will put 2 seperated words on different lines

sed "s/(.*)/\n/g" | 
#Replaces words in paranthesis by newline 

sort -u | 
#Sorts all the lines and prints a line once

comm -23 - words |
#Compares the lines of input  with the lines file words
#and prints the lines unique to the input

grep "^[pk\' mnwlhaeiou]\{1,\}$"
#Prints only those words that are formed by the
#Hawaiian letters. This eliminates left-over
#English words.


#
